import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  karnowebSidebar: [{type: 'autogenerated', dirName: 'karnoweb'}],
  packagesSidebar: [{type: 'autogenerated', dirName: 'packages'}],
};

export default sidebars;
